### ISSUE TITLE
Cards update

### ISSUE THREAD

**Issue by hdJerry** [smartcontractkit/blockchain-developer-hub#321]
- [x] update spacing between title and description
https://www.figma.com/file/9eqpfWUrL3gAQ6Royvl75u?node-id=10741:68075#242556316 
- [x] update font style https://www.figma.com/file/9eqpfWUrL3gAQ6Royvl75u?node-id=10741:68075#242556057
- [x] share icon hover effect https://www.figma.com/file/9eqpfWUrL3gAQ6Royvl75u?node-id=10741:67613#242548940
- [x] update font style to match design sub heading https://www.figma.com/file/9eqpfWUrL3gAQ6Royvl75u?node-id=10741:67613#242550408
- [x] add more paddings on sides of tag https://www.figma.com/file/9eqpfWUrL3gAQ6Royvl75u?node-id=10741:67613#242550791
- [x] check the top padding for all such cards https://www.figma.com/file/9eqpfWUrL3gAQ6Royvl75u?node-id=10741:67613#242549874
