### ISSUE TITLE
Ecosystem page updates

### ISSUE THREAD

**Issue by hdJerry** [smartcontractkit/blockchain-developer-hub#329]
- [x] update the pink gradient https://www.figma.com/file/9eqpfWUrL3gAQ6Royvl75u?node-id=10741:68559#242573358
- [x] Responsiveness https://www.figma.com/file/9eqpfWUrL3gAQ6Royvl75u?node-id=10741:70182#242571410
- [x] background image https://www.figma.com/file/9eqpfWUrL3gAQ6Royvl75u?node-id=10741:68559#242570809
- [x] Update explore ecosystem button text style https://www.figma.com/file/9eqpfWUrL3gAQ6Royvl75u?node-id=10741:68559#242568824
- [x] update `Check study roadmap` text https://www.figma.com/file/9eqpfWUrL3gAQ6Royvl75u?node-id=10741:69371#244185271
